services:
  - type: web
    name: jogodaforca
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn forca.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: forca.settings
      - key: PYTHON_VERSION
        value: 3.10
